### ISSUE TITLE
privilege problem & something seems wrong

### ISSUE THREAD

**Issue by xzer** [vkandy/simhash-js#1]
At first,  there is an access privilege problem of method "similarity", since it was declared as var, so it can not be access from outside. I solved this problem, but

Secondly, the calling of "simhash.of(xxx)" will always return 0, so I can't get any meaningful result.
By the way, the Jenkins Hash returns 0 for many inputs, I don't know whether it is correct.

**Comment by vkandy** [comment]
Thanks. I will run some tests and update this ticket today or Monday.

**Comment by X-Bird** [comment]
I got the same problem...

**Comment by bitsofparag** [comment]
Doesn't seem fixed. Any updates?

**Comment by vkandy** [comment]
Can be closed due to #6
