### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by xblanc33** [vkandy/simhash-js#5]
Hi,

Would be awesome to publish simhash-js in npm.

Thanks

**Comment by xblanc33** [comment]
And if you can put it into a node module, that would be perfect ;)

**Comment by vkandy** [comment]
@xblanc33 thanks! I wanted to add this as an npm module when I first wrote it in Node 0.8 version. But I wasn't satisfied it was prod ready and kept postponing ;) If you are interested or have the time please feel free to add and push as an npm module.

**Comment by xblanc33** [comment]
I forked it.
Can you try : https://github.com/xblanc33/simhash-js
Then you can easily import (I can manage a pull-request if you want).
then npm publish ;)

tell me

**Comment by vkandy** [comment]
Xavier, That was an incredible effort! I've merged your pull request and published to npm: https://www.npmjs.com/package/simhash-js

Hope all is good. Thank you!!

**Comment by xblanc33** [comment]
Thanks,

 

It’s good J

 

 

 

De : Vijay Kandy [mailto:notifications@github.com] 
Envoyé : jeudi 29 juin 2017 23:39
À : vkandy/simhash-js <simhash-js@noreply.github.com>
Cc : Xavier Blanc <xavier.blanc@labri.fr>; Mention <mention@noreply.github.com>
Objet : Re: [vkandy/simhash-js] npm install (#5)

 

Xavier, That was an incredible effort! I've merged your pull request and published to npm: https://www.npmjs.com/package/simhash-js

Hope all is good. Thank you!!
